#---- GENERAL
GPU: 0
VERBOSE: False

#---- PATHS
MODEL_DIR: 'bin/'
RESULTS_DIR: 'results/'
LOG_DIR: 'logs/'
MODEL_NAME: 'AcT'

#---- DATASET
SPLITS: 3
FOLDS: 10
SEEDS: [11331, 11435, 12123, 53453, 42344, 24234, 65747, 84443, 29345, 99543]
VAL_SIZE: 0.1
CHANNELS: 4
SUBSAMPLE: 1
DATASET: 'openpose'
LEGACY: False
openpose:
    KEYPOINTS: 13
    CLASSES: 20
    FRAMES: 30
posenet:
    KEYPOINTS: 13
    CLASSES: 20
    FRAMES: 30
openpose_legacy:
    KEYPOINTS: 13
    CLASSES: 20
    FRAMES: 30
posenet_legacy:
    KEYPOINTS: 17
    CLASSES: 20
    FRAMES: 30
movenet:
    KEYPOINTS: 13
    CLASSES: 20
    FRAMES: 30
kinetics:
    KEYPOINTS: 18
    CLASSES: 400
    FRAMES: 300
LABELS: ['standing','check-watch','cross-arms','scratch-head','sit-down','get-up','turn-around','walking','wave1','boxing',
         'kicking','pointing','pick-up','bending','hands-clapping','wave2','jogging','jumping','pjump','running']

#---- AUGMENTATION
FLIP_P: 0.5
RN_STD: 0.03

#---- MODEL
#PATCH_SIZE: 1
MODEL_SIZE: 'micro'
POS_EMB: #'utils/pos_emb.npy'
micro:        
    N_HEADS: 1
    N_LAYERS: 4
    EMBED_DIM: 64
    DROPOUT: 0.3
    MLP: 256
small:    
    N_HEADS: 2
    N_LAYERS: 5
    EMBED_DIM: 128
    DROPOUT: 0.3
    MLP: 256
base:
    N_HEADS: 3
    N_LAYERS: 6
    EMBED_DIM: 192
    DROPOUT: 0.3
    MLP: 256
large:
    N_HEADS: 4
    N_LAYERS: 6
    EMBED_DIM: 256
    DROPOUT: 0.4
    MLP: 512

#---- TRAINING SETTINGS 
SCHEDULER: True
N_EPOCHS: 350       
BATCH_SIZE: 512
WEIGHT_DECAY: 0.0001  
WARMUP_PERC: 0.3  
STEP_PERC: 0.8
LR_MULT: 1

#---- RANDOM SEARCH
N_TRIALS: 5

#---- TEST SETTINGS
WEIGHTS: 'bin/AcT_micro.h5'